# Generated by Django 5.0.1 on 2024-01-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tipo',
            new_name='tipo_cliente',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_tarjeta',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
