# Generated by Django 5.0.1 on 2024-01-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_rename_tipo_cliente_tipo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cedula',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_cliente',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
