# Generated by Django 5.0.1 on 2024-01-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_cedula_reserva_cliente_reserva_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_tarjeta',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
