# Generated by Django 5.0.1 on 2024-01-27 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_reserva_numero_tarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Gerente', 'Gerente'), ('Administrador', 'Administrador'), ('Empleado', 'Empleado')], default='Empleado', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hombre', models.CharField(default='Hombre', max_length=10)),
                ('mujer', models.CharField(default='Mujer', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('fechaIngreso', models.DateField()),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cargo')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.genero')),
            ],
        ),
    ]
