# Generated by Django 5.0.1 on 2024-02-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_user_apellidos_user_nombres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
