# Generated by Django 5.0.1 on 2024-02-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tiempo',
            field=models.FloatField(default=0),
        ),
    ]
