# Generated by Django 5.0.1 on 2024-02-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_alter_reserva_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_tarjeta',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
