# Generated by Django 5.0.1 on 2024-02-09 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_alter_reserva_numero_tarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('precio', models.FloatField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('tipo_pago', models.CharField(max_length=20)),
                ('numero_tarjeta', models.CharField(default=None, max_length=30)),
                ('total_pagar', models.FloatField(default=None)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.habitacion')),
            ],
        ),
    ]
