# Generated by Django 5.0.1 on 2024-02-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
    ]
