# Generated by Django 5.0.1 on 2024-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_pedido_facturado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='facturado',
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserva_terminada',
            field=models.BooleanField(default=False),
        ),
    ]
