# Generated by Django 5.0.1 on 2024-02-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='date_joined',
            new_name='fecha_de_ingreso',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fechaNacimiento',
            new_name='fecha_de_nacimiento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('', '-----'), ('GERENTE', 'GERENTE'), ('ADMINISTRADOR', 'ADMINISTRADOR'), ('EMPLEADO', 'EMPLEADO')], max_length=13),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('', '-----'), ('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
